### ISSUE TITLE
`fp/normalize-params` gives different results with keyword params

### ISSUE THREAD

**Issue by theJohnnyBrown** [jkk/formative#10]
Thanks for the handy library!

I'm running into a problem trying to use checkbox fields with `wrap-keyword-params`.

See two params maps, extracted from a test application, one with `wrap-keyword-params` and one without. "disclaimer" is the name of a field that looks like `{:name :disclaimer :type :checkbox}`

`(def pms {"submit" "Submit", "disclaimer" ["false" "true"]})`

`(def kpms {:submit "Submit", :disclaimer ["false" "true"]})`

`(#'fp/normalize-params pms)`
`;;=> {"disclaimer" "true", "submit" "Submit"}`

`(#'fp/normalize-params kpms)`
`;;=> {"submit" "Submit", "disclaimer" ["false" "true"]}`

The keyword version causes a problem later when we call something like

``` clojure
(parse-input {:datatype :boolean} ["false" "true"])
;;=> java.lang.IllegalArgumentException
;;=> No matching method found: valueOf
;;=> parse.clj:43
;;=> ...
```

**Comment by yayitswei** [comment]
Thanks for filing this issue @theJohnnyBrown, I ran into the same problem and solved it by using `ring.middleware.nested-params/wrap-nested-params`. Might be a good idea to add it to the README as a requirement so other people don't trip over this.

**Comment by yayitswei** [comment]
I should note that I got it working after adding @theJohnnyBrown's fix for `normalize-params`. I'm not sure what other effects this has, so not going to issue a PR for now.
