### ISSUE TITLE
Suggestion: Don't use :nobr in formative.render

### ISSUE THREAD

**Issue by theJohnnyBrown** [jkk/formative#35]
The problem for me is using formative-generated hiccup vectors in [sablono](https://github.com/r0man/sablono/blob/master/src/sablono/interpreter.cljx#L49), but [lack of support](https://github.com/facebook/react/blob/master/src/browser/ReactDOM.js#L130) for the tag in Reactjs.DOM is the underlying issue. Also, the w3c [discourages its use](http://www.w3.org/wiki/HTML/Elements/nobr).

**Comment by iku000888** [comment]
Hey @theJohnnyBrown @bensu 

Sorry for the long term silence of the project.
I got write access to this repo from jkk and I would be happy to take a patch for this.

On a separate note, do you happen to have any insights on whether or not long lines would suddenly start wrapping by simply removing the :nobr on some browsers?
Have not investigated it but just imagined the original intention by reading this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/nobr.

**Comment by theJohnnyBrown** [comment]
Yes, it's possible that long lines may start wrapping if the `<nobr>` tag were removed, but again, this is non-standard HTML and the same effect can be accomplished with CSS.

**Comment by iku000888** [comment]
Thanks for confirming.
Just to be clear I am all for removing the :nobr, and just want to explore how the potential surprise can be mitigated. Please do feel free to go on with a PR .
