### ISSUE TITLE
Horizontal Bootstrap 3 Form Layout

### ISSUE THREAD

**Issue by pate** [jkk/formative#39]
How can I make horizontal Bootstrap 3 layouts like in the [Bootstrap documentation](http://getbootstrap.com/css/#forms-horizontal)?

**Comment by iku000888** [comment]
I think providing the
```
:renderer :bootstrap3-stacked
```
Would make it look like that.

Let me know if I am now understanding the question correctly!

**Comment by iku000888** [comment]
Please re-open if I did not understand your question correctly.
