### ISSUE TITLE
dommy is outdated

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [jkk/formative#40]

**Comment by lkrubner** [comment]
Is this still true? Dommy was updated on Apr 23, 2015.

**Comment by BenjaminVanRyseghem** [comment]
@lkrubner I do not understand your comment

**Comment by lkrubner** [comment]
@BenjaminVanRyseghem -- sorry, perhaps I misunderstood your remark. "Dommy is outdated" sounds like the library is no longer being updated. But it was updated after your wrote your remark, so perhaps Dommy is no longer outdated? Perhaps it is being actively maintained?

**Comment by BenjaminVanRyseghem** [comment]
@lkrubner sorry for the late answer :smile:

Dommy it still active, but the dependency to dommy points to a very old version of dommy.
But it looks like this project's dead

**Comment by iku000888** [comment]
Personally not a high priority, but updating to the latest dommy has API level breakage.
If that can be taken care of, I am willing to accept a PR.

Quoting Dommy's README:
``` 
Upgrading to 1.0.0+ from 0.X.Y

Version "1.0.0" includes breaking API changes. Here's a quick overview of what's changed:

    dommy.template namespace and all related templating features (node, deftemplate, etc) have been removed from the library.
    Simplified namespace structure. Everything in dommy.macros and dommy.attrs has been moved into dommy.core

https://github.com/plumatic/dommy/pull/85
```

**Comment by iku000888** [comment]
Looks like it is taken care in formidable.
@BenjaminVanRyseghem 
Wink wink ;)

**Comment by BenjaminVanRyseghem** [comment]
Please tell me what you want me to do :smile:

**Comment by iku000888** [comment]
@BenjaminVanRyseghem 
I am thinking it would just be 
- updating the dommy dependency to the latest
- backporting your https://github.com/teamwall/formidable/blob/master/src/formidable/dom.cljs to https://github.com/jkk/formative/blob/master/src/formative/dom.cljs
(Note the sel sel1 macros are located in a different ns, which is why there is a breakage.)
- Plus making sure that it does what it is supposed to do.
(Sorry, not too familiar with the cljs side of formative, so need help in that part)

**Comment by iku000888** [comment]
So I went ahead and got my hands dirty.
I am thinking it boils down to how to replace dommy.macros/node, which got removed entirely from dommy.

Some options I can think of:
- Fixing it inevitably forces us to pick an alternative cljs hiccup implementation (FYI I see formidable went for crate, but given x many cljs hiccup implementations would like some time to investigate options)
- Copying the old implementation from dommy into the project.
- Something else

Would appreciate any feedback!

**Comment by iku000888** [comment]
Quickly searched ClojureScript hiccup Alternatives:

https://github.com/ibdknox/crate
https://github.com/teropa/hiccups
https://github.com/jeluard/hipo

hipo is tempting as it is a descendant of the dommy code... 
But on the otherhand I do not feel comfortable adding a hiccup rendering solution just to fix a single function in formative.dom.

**Comment by iku000888** [comment]
For anyone interested, here is a PR that removes dommy as a dependency.
https://github.com/jkk/formative/pull/57

Would appreciate if you can catch any dubious errors!

**Comment by iku000888** [comment]
Fixed and testing appreciated!
 https://clojars.org/formative/versions/0.8.10-rc
