### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by BenjaminVanRyseghem** [jkk/formative#41]

**Comment by arnaudbos** [comment]
Need dommy upgrade, moving to your fork, thx @BenjaminVanRyseghem !

**Comment by iku000888** [comment]
I asked jkk to give me commit rights (which he did)
and I will spend some time maintaining it from now on, 
so it is not dead, I guess :)

**Comment by BenjaminVanRyseghem** [comment]
I forked your project a while ago [here](https://github.com/teamwall/formidable)

Maybe you would like me to do a PR to you or something?

**Comment by iku000888** [comment]
That definitely would be great!

**Comment by iku000888** [comment]
@BenjaminVanRyseghem Just a heads up,
I would first like to set up a ci environment + move the tests to cljc,
which would make the minimum version of clojure 1.7.
Hope that does not an issue for you.
