### ISSUE TITLE
`required` DOM attribute

### ISSUE THREAD

**Issue by danielbraun** [jkk/formative#63]
The `required` DOM attribute is filtered out when rendering a select box field, for instance:
https://github.com/jkk/formative/blob/33e553c690b99e3c2de58f281a39631576a819c7/src/formative/render.cljc#L146-L149

It's quite a useful attribute, should probably add it to the field whitelist above.

**Comment by iku000888** [comment]
@danielbraun Would be happy to accept a PR!
