### ISSUE TITLE
Can't upload file

### ISSUE THREAD

**Issue by punit-allstreet** [jkk/formative#68]
I am rendering a form by using the `handle-submit` fn as I don't want the submit button to fire a post request on clicking.

But I have a file upload field in my form. And when the [`formative.dom/handle-submit`](https://github.com/jkk/formative/blob/8904e74d3019ccb9e9702545454907108a471add/src/formative/dom.cljs#L122) fn calls the 
[`formative.dom/serialize`](https://github.com/jkk/formative/blob/8904e74d3019ccb9e9702545454907108a471add/src/formative/dom.cljs#L16) fn, it removes the [file input](https://github.com/jkk/formative/blob/8904e74d3019ccb9e9702545454907108a471add/src/formative/dom.cljs#L38) field type while it's serialising form parameters and hence the [`formative.parse/parse-input`](https://github.com/jkk/formative/blob/8904e74d3019ccb9e9702545454907108a471add/src/formative/parse.cljc#L206) fn is never called.

So how can I do file upload without having the default `POST` behaviour?

**Comment by iku000888** [comment]
Hi @punit-allstreet !

I think I can't help much directly as I have not used the formative.dom facility myself.
IMO it is a method that was a workaround for the lack of react back in the days, so if it is for a new page I strongly would recommend a react based solution such as [https://github.com/reagent-project/reagent-forms#file](reagent-forms).

Other than that happy to look at a minimal project or accept PRs!
